version: '3'
services:
  react-app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: app-write
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - app
    volumes:
      - ./src:/app/src
      - ./app/node_modules

networks:
  app:
    driver: bridge
